- name: Cari backup WAR terbaru
  ansible.builtin.shell:
    cmd: ls -t /root/app/jenkins/backup/*.war | head -1
  register: latest_backup
  changed_when: false

- name: Stop Jenkins
  ansible.builtin.systemd:
    name: jenkins-custom
    state: stopped

- name: Restore backup WAR terbaru
  ansible.builtin.copy:
    src: "{{ latest_backup.stdout }}"
    dest: "{{ jenkinsbvk_war_path }}"
    remote_src: yes

- name: Start Jenkins
  ansible.builtin.systemd:
    name: jenkins-custom
    state: started

- name: Tunggu Jenkins aktif
  ansible.builtin.wait_for:
    port: "{{ jenkinsbvk_port }}"
    timeout: 300
