    - name: Create Rancher container
      docker_container:
        name: "{{ rancher_container_name }}"
        image: "{{ rancher_image }}"
        state: started
        restart_policy: always
        privileged: true
        ports:
          - "{{ rancher_http_port }}:8080"
          - "{{ rancher_https_port }}:8443"
        volumes:
          - /opt/rancher:/var/lib/rancher

    - name: Wait for Rancher port to be open
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ rancher_https_port }}"
        timeout: 600
        state: started

    - name: Wait for Rancher Web UI to become available
      uri:
        url: "https://{{ inventory_hostname }}:{{ rancher_https_port }}"
        method: GET
        validate_certs: no
        status_code: 200
      register: rancher_ui
      retries: 60
      delay: 10
      until: rancher_ui.status == 200

