- name: Cek apakah mirror id.archive.ubuntu.com digunakan
  shell: grep -q 'http://id.archive.ubuntu.com' /etc/apt/sources.list
  register: check_id_mirror
  ignore_errors: yes

- name: Ganti mirror repo dari id.archive.ubuntu.com ke archive.ubuntu.com
  replace:
    path: /etc/apt/sources.list
    regexp: 'http://id.archive.ubuntu.com'
    replace: 'http://archive.ubuntu.com'
  when: check_id_mirror.rc == 0

- name: Ensure directory for apt keyrings exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Webmin GPG key
  get_url:
    url: http://www.webmin.com/jcameron-key.asc
    dest: /etc/apt/keyrings/webmin.asc
    mode: '0644'

- name: Add Webmin APT repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/webmin.asc] http://download.webmin.com/download/repository sarge contrib"
    state: present
    filename: webmin

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Webmin
  apt:
    name: webmin
    state: present

#- name: Set Webmin root password using htpasswd
 # command: htpasswd -b /etc/webmin/miniserv.users root "{{ password }}"
  #notify: Restart Webmin

#- name: Restart Webmin
 # service:
  #  name: webmin
   # state: restarted

- name: Set Webmin to use internal authentication (auth_mode=webmin)
  lineinfile:
    path: /etc/webmin/config
    line: "auth_mode=webmin"
    create: yes
  notify: Restart Webmin

- name: Wait until miniserv.users exists
  wait_for:
    path: /etc/webmin/miniserv.users
    timeout: 30

#- name: Set Webmin root password using htpasswd
 # command: htpasswd -b /etc/webmin/miniserv.users root "{{ password }}"
- name: Set Webmin root password using changepass.pl
  command: /usr/share/webmin/changepass.pl /etc/webmin root "{{ password }}"
  notify: Restart Webmin

- name: Restart Webmin after setting password
  service:
    name: webmin
    state: restarted

- name: Ensure Webmin service is started
  service:
    name: webmin
    state: started
    enabled: yes

# Opsional - jika menggunakan UFW dan butuh buka port Webmin
- name: Allow Webmin port 10000 in firewall
  ufw:
    rule: allow
    port: '10000'
    proto: tcp
  when: ansible_facts.os_family == 'Debian'
