- name: ANSIBLE-COLONYLABS@2024
  hosts: server
  remote_user: farman17
  become: yes
  become_method: sudo
  vars:
    ansible_become_pass: "{{ vault_sudo_password }}"
  roles:
    - update
    #- dependen
    #- nginx
    #- docker
    #- corosync-cluster
    #- corosync-client
    #- node_exporter
    #- prometheus
    #- grafana
    #- harbor
    #- k3s-kubernetes
    #- awx-ansible
    #- minio
    #- webmin
    #- bind9_dns
    #- jenkins
    #- redismaster
    #- redis-replica
    - rancher
    #- SUMMARY
