- name: ANSIBLE-COLONYLABS@2024
  hosts: server
  remote_user: server1
  become: yes
  become_method: sudo
  vars:
    ansible_become_pass: "{{ vault_sudo_password }}"
  roles:
    - update
    #- dependen
    #- nginx
    - docker
    #- corosync-cluster
    #- corosync-client
    #- node_exporter
    #- grafana
    #- prometheus
    #- harbor
    #- k3s-kubernetes
    #- awx-ansible
    #- minio
    #- webmin
    #- bind9_dns
    - jenkins
    #- redismaster
    #- redisslave
    #- kafka
    #- kafka_ui
    #- rancher
    #- SUMMARY
