- name: ANSIBLE-COLONYLABS@2024
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - update
    - dependen
    - nginx
    - docker
    #- corosync-cluster
    #- corosync-client
    #- node_exporter
    #- grafana
    #- prometheus
    #- harbor
    #- k3s-kubernetes
    #- awx-ansible
    #- minio
    #- webmin
    #- bind9_dns
    #- jenkins
    #- jenkinsbvk
    #- jenkinsbvk_upgrade
    #- jenkinsbvk_rollback
    #- java_switch
    #- redismaster
    #- redisslave
    #- kafka
    #- kafka_ui
    #- rancher
    #- SUMMARY
